// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from '@/types/supabase';

const SUPABASE_URL = "https://iastodpapkikrbobjasa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhc3RvZHBhcGtpa3Jib2JqYXNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMDQ5MzYsImV4cCI6MjA2MzU4MDkzNn0.FeJYQy5pYr1Dr86mPFCOYrXxsloqIF6jPVPAT_ww8CI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);